AllCops:
  DisplayCopNames: true
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/ParameterLists:
  Max: 8
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/ModuleLength:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods: [require, raise, include, attr_reader, refute, assert]
  Exclude: [Gemfile*, Rakefile, kubeclient.gemspec]
Style/FileName:
  Exclude: [Gemfile*]
Security/MarshalLoad:
  Exclude: [test/**/*]
